minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
trustLockfile: false
blockExoticSubdeps: true
verifyStoreIntegrity: true
strictStorePkgContentCheck: true
strictDepBuilds: true
allowBuilds:
  fsevents: false
